// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("DailyTarget")]
    [Index(nameof(StartDate), Name = "DailyTarget_UNIQUE_StartDate", IsUnique = true)]
    public partial class DailyTarget
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        public int Calories { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Protein { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Carbs { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Fats { get; set; }
    }
}