// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("IngredientReference")]
    [Index(nameof(Name), Name = "IngredientReference_UNIQUE_Name", IsUnique = true)]
    public partial class IngredientReference
    {
        public IngredientReference()
        {
            MealChanges = new HashSet<MealChange>();
            RecipeIngredients = new HashSet<RecipeIngredient>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(1000)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal PerAmount { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string UnitName { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Protein { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Fat { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Carbs { get; set; }
        public int Calories { get; set; }

        [InverseProperty(nameof(MealChange.IngredientReference))]
        public virtual ICollection<MealChange> MealChanges { get; set; }
        [InverseProperty(nameof(RecipeIngredient.IngredientReference))]
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
    }
}