// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("MealType")]
    [Index(nameof(Name), Name = "MealType_UNIQUE_Name", IsUnique = true)]
    public partial class MealType
    {
        public MealType()
        {
            Meals = new HashSet<Meal>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(1000)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty(nameof(Meal.MealType))]
        public virtual ICollection<Meal> Meals { get; set; }
    }
}