// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("Meal")]
    [Index(nameof(RecipeId), nameof(PlannedDate), nameof(MealTypeId), Name = "Meal_UNIQUE_RecipeId_PlannedDate_MealTypeId", IsUnique = true)]
    public partial class Meal
    {
        public Meal()
        {
            MealChanges = new HashSet<MealChange>();
        }

        [Key]
        public int Id { get; set; }
        public int RecipeId { get; set; }
        [Column(TypeName = "date")]
        public DateTime PlannedDate { get; set; }
        public int MealTypeId { get; set; }

        [ForeignKey(nameof(MealTypeId))]
        [InverseProperty("Meals")]
        public virtual MealType MealType { get; set; }
        [ForeignKey(nameof(RecipeId))]
        [InverseProperty("Meals")]
        public virtual Recipe Recipe { get; set; }
        [InverseProperty(nameof(MealChange.Meal))]
        public virtual ICollection<MealChange> MealChanges { get; set; }
    }
}