// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("RecipeStep")]
    [Index(nameof(RecipeId), nameof(StepNumber), Name = "RecipeStep_UNIQUE_RecipeId_StepNumber", IsUnique = true)]
    public partial class RecipeStep
    {
        [Key]
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public int StepNumber { get; set; }
        [Required]
        public string Text { get; set; }

        [ForeignKey(nameof(RecipeId))]
        [InverseProperty("RecipeSteps")]
        public virtual Recipe Recipe { get; set; }
    }
}