// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("RecipeIngredient")]
    [Index(nameof(RecipeId), nameof(IngredientReferenceId), Name = "RecipeIngredient_UNIQUE_RecipeId_IngredientReferenceId", IsUnique = true)]
    public partial class RecipeIngredient
    {
        [Key]
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public int IngredientReferenceId { get; set; }
        [Column(TypeName = "decimal(10, 4)")]
        public decimal Amount { get; set; }

        [ForeignKey(nameof(IngredientReferenceId))]
        [InverseProperty("RecipeIngredients")]
        public virtual IngredientReference IngredientReference { get; set; }
        [ForeignKey(nameof(RecipeId))]
        [InverseProperty("RecipeIngredients")]
        public virtual Recipe Recipe { get; set; }
    }
}