// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MealPlan.Db.Model
{
    [Table("Recipe")]
    [Index(nameof(Name), Name = "Recipe_UNIQUE_Name", IsUnique = true)]
    public partial class Recipe
    {
        public Recipe()
        {
            RecipeIngredients = new HashSet<RecipeIngredient>();
            RecipeSteps = new HashSet<RecipeStep>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(1000)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty(nameof(RecipeIngredient.Recipe))]
        public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; }
        [InverseProperty(nameof(RecipeStep.Recipe))]
        public virtual ICollection<RecipeStep> RecipeSteps { get; set; }
    }
}