CREATE TABLE [dbo].[MealType]
(
	[Id] INT NOT NULL,
	[Name] VARCHAR(1000) NOT NULL,
	CONSTRAINT [MealType_PRIMARY_KEY_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [MealType_UNIQUE_Name] UNIQUE NONCLUSTERED ([Name] ASC)
)
